/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksNewRouteImport } from './routes/books.new'
import { Route as BooksBookIdVisionRouteImport } from './routes/books.$bookId.vision'
import { Route as BooksBookIdStoryBibleRouteImport } from './routes/books.$bookId.story-bible'
import { Route as BooksBookIdManuscriptRouteImport } from './routes/books.$bookId.manuscript'
import { Route as BooksBookIdInsightsRouteImport } from './routes/books.$bookId.insights'
import { Route as BooksBookIdChatRouteImport } from './routes/books.$bookId.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdVisionRoute = BooksBookIdVisionRouteImport.update({
  id: '/$bookId/vision',
  path: '/$bookId/vision',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdStoryBibleRoute = BooksBookIdStoryBibleRouteImport.update({
  id: '/$bookId/story-bible',
  path: '/$bookId/story-bible',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdManuscriptRoute = BooksBookIdManuscriptRouteImport.update({
  id: '/$bookId/manuscript',
  path: '/$bookId/manuscript',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdInsightsRoute = BooksBookIdInsightsRouteImport.update({
  id: '/$bookId/insights',
  path: '/$bookId/insights',
  getParentRoute: () => BooksRoute,
} as any)
const BooksBookIdChatRoute = BooksBookIdChatRouteImport.update({
  id: '/$bookId/chat',
  path: '/$bookId/chat',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/books/new': typeof BooksNewRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/chat': typeof BooksBookIdChatRoute
  '/books/$bookId/insights': typeof BooksBookIdInsightsRoute
  '/books/$bookId/manuscript': typeof BooksBookIdManuscriptRoute
  '/books/$bookId/story-bible': typeof BooksBookIdStoryBibleRoute
  '/books/$bookId/vision': typeof BooksBookIdVisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/books/new': typeof BooksNewRoute
  '/books': typeof BooksIndexRoute
  '/books/$bookId/chat': typeof BooksBookIdChatRoute
  '/books/$bookId/insights': typeof BooksBookIdInsightsRoute
  '/books/$bookId/manuscript': typeof BooksBookIdManuscriptRoute
  '/books/$bookId/story-bible': typeof BooksBookIdStoryBibleRoute
  '/books/$bookId/vision': typeof BooksBookIdVisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/books/new': typeof BooksNewRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/chat': typeof BooksBookIdChatRoute
  '/books/$bookId/insights': typeof BooksBookIdInsightsRoute
  '/books/$bookId/manuscript': typeof BooksBookIdManuscriptRoute
  '/books/$bookId/story-bible': typeof BooksBookIdStoryBibleRoute
  '/books/$bookId/vision': typeof BooksBookIdVisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/login'
    | '/settings'
    | '/books/new'
    | '/books/'
    | '/books/$bookId/chat'
    | '/books/$bookId/insights'
    | '/books/$bookId/manuscript'
    | '/books/$bookId/story-bible'
    | '/books/$bookId/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/books/new'
    | '/books'
    | '/books/$bookId/chat'
    | '/books/$bookId/insights'
    | '/books/$bookId/manuscript'
    | '/books/$bookId/story-bible'
    | '/books/$bookId/vision'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/login'
    | '/settings'
    | '/books/new'
    | '/books/'
    | '/books/$bookId/chat'
    | '/books/$bookId/insights'
    | '/books/$bookId/manuscript'
    | '/books/$bookId/story-bible'
    | '/books/$bookId/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/new': {
      id: '/books/new'
      path: '/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId/vision': {
      id: '/books/$bookId/vision'
      path: '/$bookId/vision'
      fullPath: '/books/$bookId/vision'
      preLoaderRoute: typeof BooksBookIdVisionRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId/story-bible': {
      id: '/books/$bookId/story-bible'
      path: '/$bookId/story-bible'
      fullPath: '/books/$bookId/story-bible'
      preLoaderRoute: typeof BooksBookIdStoryBibleRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId/manuscript': {
      id: '/books/$bookId/manuscript'
      path: '/$bookId/manuscript'
      fullPath: '/books/$bookId/manuscript'
      preLoaderRoute: typeof BooksBookIdManuscriptRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId/insights': {
      id: '/books/$bookId/insights'
      path: '/$bookId/insights'
      fullPath: '/books/$bookId/insights'
      preLoaderRoute: typeof BooksBookIdInsightsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/$bookId/chat': {
      id: '/books/$bookId/chat'
      path: '/$bookId/chat'
      fullPath: '/books/$bookId/chat'
      preLoaderRoute: typeof BooksBookIdChatRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksNewRoute: typeof BooksNewRoute
  BooksIndexRoute: typeof BooksIndexRoute
  BooksBookIdChatRoute: typeof BooksBookIdChatRoute
  BooksBookIdInsightsRoute: typeof BooksBookIdInsightsRoute
  BooksBookIdManuscriptRoute: typeof BooksBookIdManuscriptRoute
  BooksBookIdStoryBibleRoute: typeof BooksBookIdStoryBibleRoute
  BooksBookIdVisionRoute: typeof BooksBookIdVisionRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksNewRoute: BooksNewRoute,
  BooksIndexRoute: BooksIndexRoute,
  BooksBookIdChatRoute: BooksBookIdChatRoute,
  BooksBookIdInsightsRoute: BooksBookIdInsightsRoute,
  BooksBookIdManuscriptRoute: BooksBookIdManuscriptRoute,
  BooksBookIdStoryBibleRoute: BooksBookIdStoryBibleRoute,
  BooksBookIdVisionRoute: BooksBookIdVisionRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
